[package]
name = "acab"
version = "0.1.0"
edition = "2024"

[dependencies]
konst = { version = "0.3.15", features = ["cmp", "iter"], default-features = false }
proc-macro2 = "1.0.92"
unicode-xid = "0.2.6"

[features]
default = ["alloc"]
alloc = []

[dev-dependencies]
quote = "1.0.37"
